import { Todo } from './Todo';
import { TodoActionType, TodoAction } from './action';

const reducer = (state: Todo[], action: TodoAction): Todo[] => {
  switch (action.type) {
    case TodoActionType.added: {
      const id =
        state
          .map((todo) => todo.id)
          .reduce((max, current) => (max < current ? current : max), 0) + 1;

      const { title, description } = action.payload;

      return [...state, { id, title, description, isCompleted: false }];
    }
    case TodoActionType.removed: {
      return state.filter((todo) => todo.id !== action.payload.id);
    }
    case TodoActionType.updated: {
      return [
        ...state.filter((todo) => todo.id !== action.payload.id),
        action.payload,
      ];
    }
    default:
      throw new Error('Use action generated by action creator.');
  }
};

export default reducer;
