import { Todo } from './Todo';
import { TodoAction } from './action';

export const initialState: Todo[] = [];
type State = typeof initialState;

export const reducer = (state: State, action: TodoAction): State => {
  switch (action.type) {
    case 'todo/added': {
      const id =
        state
          .map((todo) => todo.id)
          .reduce((max, current) => Math.max(max, current), 0) + 1;

      return [...state, { id, isCompleted: false, ...action.payload }];
    }
    case 'todo/removed': {
      return state.filter((todo) => todo.id !== action.payload.id);
    }
    case 'todo/updated': {
      return [
        ...state.filter((todo) => todo.id !== action.payload.id),
        action.payload,
      ];
    }
    default: {
      const _: never = action;
      throw new Error('Use action generated by creator.');
    }
  }
};
