import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useTheme } from '@/contexts/ThemeContext';

const Home: NextPage = () => {
  const { theme, toggleTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center">
        <h1 className="my-10">HOME</h1>
        <div className="flex gap-x-2">
          <label htmlFor="dark-mode-checkbox">Dark Mode:</label>
          <input
            type="checkbox"
            id="dark-mode-checkbox"
            checked={theme === 'dark'}
            onChange={() => toggleTheme()}
          />
        </div>
        <Link
          href="/about"
          className="hover:text-accent hover:underline focus:text-accent focus:underline"
        >
          Go to about page →
        </Link>
      </main>
    </>
  );
};

export default Home;
